// vue/vue-todo-app/src/components/Sidebar.vue
<template>
  <aside class="sidebar" :class="{ 'sidebar-open': isOpen, 'sidebar-closed': !isOpen }">
    <div class="sidebar-header">
      <h2 class="sidebar-title" v-show="isOpen">Todo App</h2>
      <button class="toggle-btn" @click="$emit('toggle')" :aria-label="isOpen ? 'Close sidebar' : 'Open sidebar'">
        <span v-if="isOpen">◀</span>
        <span v-else>▶</span>
      </button>
    </div>
    
    <nav class="sidebar-nav">
      <router-link 
        to="/" 
        class="nav-item"
        :class="{ 'nav-item-collapsed': !isOpen }"
        active-class="active"
      >
        <span class="nav-icon">📊</span>
        <span class="nav-text" v-show="isOpen">Dashboard</span>
      </router-link>
      
      <router-link 
        to="/todos" 
        class="nav-item"
        :class="{ 'nav-item-collapsed': !isOpen }"
        active-class="active"
      >
        <span class="nav-icon">✓</span>
        <span class="nav-text" v-show="isOpen">All Todos</span>
      </router-link>
      
      <router-link 
        to="/projects" 
        class="nav-item"
        :class="{ 'nav-item-collapsed': !isOpen }"
        active-class="active"
      >
        <span class="nav-icon">📁</span>
        <span class="nav-text" v-show="isOpen">Projects</span>
      </router-link>
    </nav>
    
    <div class="sidebar-footer" v-show="isOpen">
      <p class="footer-text">© 2026 Todo App</p>
    </div>
  </aside>
</template>

<script>
export default {
  name: 'Sidebar',
  props: {
    isOpen: {
      type: Boolean,
      default: true
    }
  },
  emits: ['toggle']
}
</script>

<style scoped>
.sidebar {
  position: fixed;
  left: 0;
  top: 0;
  height: 100vh;
  background: linear-gradient(180deg, #2c3e50 0%, #34495e 100%);
  color: white;
  transition: width 0.3s ease;
  z-index: 1000;
  display: flex;
  flex-direction: column;
  box-shadow: 2px 0 10px rgba(0, 0, 0, 0.1);
}

.sidebar-open {
  width: 250px;
}

.sidebar-closed {
  width: 60px;
}

.sidebar-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 20px 15px;
  border-bottom: 1px solid rgba(255, 255, 255, 0.1);
}

.sidebar-title {
  margin: 0;
  font-size: 24px;
  font-weight: 600;
  white-space: nowrap;
  overflow: hidden;
}

.toggle-btn {
  background: rgba(255, 255, 255, 0.1);
  border: none;
  color: white;
  width: 32px;
  height: 32px;
  border-radius: 4px;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: background 0.2s;
}

.toggle-btn:hover {
  background: rgba(255, 255, 255, 0.2);
}

.sidebar-nav {
  flex: 1;
  padding: 20px 0;
}

.nav-item {
  display: flex;
  align-items: center;
  padding: 12px 20px;
  color: rgba(255, 255, 255, 0.8);
  text-decoration: none;
  transition: all 0.2s;
  margin: 4px 10px;
  border-radius: 6px;
}

.nav-item:hover {
  background: rgba(255, 255, 255, 0.1);
  color: white;
}

.nav-item.active {
  background: rgba(255, 255, 255, 0.2);
  color: white;
  font-weight: 600;
}

.nav-item-collapsed {
  justify-content: center;
  padding: 12px;
}

.nav-icon {
  font-size: 20px;
  min-width: 24px;
}

.nav-text {
  margin-left: 12px;
  white-space: nowrap;
}

.sidebar-footer {
  padding: 20px;
  border-top: 1px solid rgba(255, 255, 255, 0.1);
  text-align: center;
}

.footer-text {
  margin: 0;
  font-size: 12px;
  color: rgba(255, 255, 255, 0.5);
}
</style>

// React/todo-app/src/components/Sidebar.tsx
import { classNames } from 'primereact/utils';

interface SidebarProps {
  activePage: string;
  onNavigate: (page: string) => void;
  collapsed: boolean;
  onToggle: () => void;
}

const menuItems = [
  { id: 'dashboard', label: 'Dashboard', icon: 'pi pi-home' },
  { id: 'kanban', label: 'Kanban Board', icon: 'pi pi-objects-column' },
  { id: 'todos', label: 'Todo List', icon: 'pi pi-list' },
  { id: 'projects', label: 'Projects', icon: 'pi pi-folder' },
];

export default function Sidebar({ activePage, onNavigate, collapsed, onToggle }: SidebarProps) {
  return (
    <div
      className={classNames('sidebar flex-shrink-0 transition-all duration-300', {
        'sidebar-collapsed': collapsed,
        'sidebar-expanded': !collapsed,
      })}
    >
      <div className="sidebar-header flex align-items-center justify-content-between p-3">
        {!collapsed && (
          <div className="logo-section flex align-items-center gap-2">
            <div className="logo-icon w-2rem h-2rem border-circle flex align-items-center justify-content-center"
              style={{ background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)' }}>
              <i className="pi pi-check-square text-white text-sm" />
            </div>
            <span className="font-bold text-lg text-white">TodoApp</span>
          </div>
        )}
        <button
          className="sidebar-toggle p-button p-component p-button-text p-button-rounded"
          onClick={onToggle}
          style={{ color: 'white' }}
        >
          <i className={classNames('pi', collapsed ? 'pi-angle-double-right' : 'pi-angle-double-left')} />
        </button>
      </div>

      <nav className="sidebar-nav mt-3">
        {menuItems.map((item) => (
          <button
            key={item.id}
            className={classNames('nav-item flex align-items-center gap-3 p-3 w-full border-none cursor-pointer transition-all duration-200', {
              'nav-item-active': activePage === item.id,
            })}
            onClick={() => onNavigate(item.id)}
            title={collapsed ? item.label : undefined}
          >
            <i className={classNames(item.icon, 'text-xl', { 'nav-icon-collapsed': collapsed })} />
            {!collapsed && <span className="font-medium">{item.label}</span>}
          </button>
        ))}
      </nav>

      {!collapsed && (
        <div className="sidebar-footer absolute bottom-0 left-0 right-0 p-3">
          <div className="user-card p-3 border-round" style={{ background: 'rgba(255,255,255,0.1)' }}>
            <div className="flex align-items-center gap-2">
              <img
                src="https://i.pravatar.cc/150?u=1"
                alt="User"
                className="w-2rem h-2rem border-circle"
              />
              <div>
                <div className="text-white font-medium text-sm">John Doe</div>
                <div className="text-300 text-xs">john@example.com</div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
